# Generated by Django 5.1.5 on 2025-02-07 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, null=True, verbose_name='Referrer')),
                ('device_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Device Type')),
                ('browser', models.CharField(blank=True, max_length=100, null=True, verbose_name='Browser')),
                ('os', models.CharField(blank=True, max_length=100, null=True, verbose_name='Operating System')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Viewed At')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_views', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Content View',
                'verbose_name_plural': 'Content Views',
                'ordering': ('-viewed_at',),
            },
        ),
    ]
